version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      -  ./client/build:/app/client/build
      -  ./server/public/sounds:/app/server/public/sounds
      -  ./client/build:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  fast-meet:
    expose:
      - 9000
    # deploy:
    #   replicas: 8
      # restart_policy:
      #   condition: always
      # update_config:
      #   parallelism: 2
      #   delay: 15s
    image: silvareal/fast-meet
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - client/.env
      - server/.env
    # command: npm run deploy
    command: npm start --prefix server
    